sudo: required

language: php

php: 
- 7.0


services:
  - docker

python:
  - 3.6

before_script:
  - docker-compose -f docker-compose.yml up --build -d
  - docker ps -a

script: make install_gf_plugin

after_script:
  - docker-compose -f docker-compose.yml down