sudo: required

language: python

services:
  - docker

python:
  - 3.6

before_script:
  - docker-compose -f docker-compose.yml up --build -d
  - docker ps -a

script: make mg_run_test_coverage

after_script:
  - docker-compose -f docker-compose.yml down